### ISSUE TITLE
How about a lib/crate?

### ISSUE THREAD

**Issue by fdncred** [jamesodhunt/rout#1]
**Is your feature request related to a problem? Please describe.**
This is cool! How about making it a crate/library so I can embed this functionality into my own program?

**Describe the solution you'd like**
a crate.

**Describe alternatives you've considered**
other `printf` kind of crates

**Comment by jamesodhunt** [comment]
Hi @fdncred - thanks for raising (and sorry I missed this - mail filters ;)

There is actually already a crate: https://crates.io/crates/rout.

Closing for now, but feel free to reopen if required...

**Comment by fdncred** [comment]
Maybe I'm misunderstanding, I meant a crate library that I can embed into my own rust program. The link you give appears to allow one to install the `rout` command versus a library.
